spring:
  datasource:
    url: jdbc:mysql:///1901_work1
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis-plus:
  mapper-locations: classpath:com/qf/dao/mapper/*.xml